name: Build OpenJDK 25
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Build Tools & Cross-Compiler
        run: |
          sudo apt update
          sudo apt -y install autoconf bash build-essential libx11-dev libxext-dev \
          libxrender-dev libxtst-dev libxt-dev libcups2-dev libfontconfig1-dev \
          libasound2-dev openjdk-21-jdk gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Clone OpenJDK 25
        run: |
          git clone --depth 1 https://github.com/openjdk/jdk jdk-source

      - name: Apply Your Patch
        run: |
          cd jdk-source
          patch -p1 < ../patches/jdk25u_android.diff || patch -p0 < ../patches/jdk25u_android.diff || echo "Патч не применился, пробуем без него"

      - name: Configure OpenJDK
        run: |
          cd jdk-source
          bash autogen.sh
          # Исправленные флаги для OpenJDK 25
          bash configure \
            --with-boot-jdk=/usr/lib/jvm/java-21-openjdk-amd64 \
            --with-debug-level=release \
            --disable-warnings-as-errors \
            --enable-headless-only \
            --openjdk-target=aarch64-linux-gnu \
            --with-jvm-variants=server \
            --with-native-debug-symbols=none
          
      - name: Build Images
        run: |
          cd jdk-source
          make images
          
      - name: Archive and Upload
        if: success()
        run: |
          # Переходим в папку с результатом, пакуем и загружаем
          cd jdk-source/build/*/images
          tar -cJf ../../../../jdk25-android-aarch64.tar.xz jdk
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Java25-Final-AArch64
          path: jdk25-android-aarch64.tar.xz
